# This is a basic workflow to help you get started with Actions

name: build-ios

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ release ]

jobs:
  build-ios:
    runs-on: macOS-latest
    steps: 
      - uses: actions/checkout@v1
      - name: Install npm dependencies
        run: |
          npm install
      - name: Install pod dependencies
        run: |
          cd example/ios && pod install    
      - name: Run fastlane setup (create key_chain)
        env:
          APPLE_ACCOUNT: ${{ secrets.APPLE_ACCOUNT }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
        run: |
          cd example/ios
          fastlane setup          
      - name: Run fastlane build
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
        run: |
          cd example/ios
          fastlane build 
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: RNCT Demo.ipa
          path: example/ios/output
